### ISSUE TITLE
Support for Actionscript tests?

### ISSUE THREAD

**Issue by karfau** [davearata/checktests#1]
If I understand your plugin correctly, it should help me to execute all tests before I can commit.

I would really liek to use it, but it seems like my tests are not found.

I have an ActionScript/Flex project that uses FlexUnit, which is supported well by Intellij Idea.

What needs to be done to support my tests?

[The project](https://github.com/karfau/as3-depending) I'm currently working on would be a complex example, but I can provide a more simple one if it helps.

I think I might also be able to help with development, but I would like to have some instructions to get started.

**Comment by karfau** [comment]
When I invoke the "Check for tests" context menu on a test directory, it throws the following error:

```
null
java.lang.NullPointerException
    at com.dacatech.checktests.TestClassDetectorImpl.findTestClasses(TestClassDetectorImpl.java:108)
    at com.dacatech.checktests.TestClassDetectorImpl$1.run(TestClassDetectorImpl.java:60)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$5.run(ProgressManagerImpl.java:269)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$TaskRunnable.run(ProgressManagerImpl.java:471)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$6.run(ProgressManagerImpl.java:281)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:178)
    at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:171)
    at com.intellij.openapi.application.impl.ApplicationImpl$10$1.run(ApplicationImpl.java:645)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:419)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:149)
```

just wanted to mention it, because maybe this point to the actual problem.
Using version 13.1.3
